name: Auto-Clean

on:
  #自动触发，详见 GitHub文档：关于触发工作流的事件
  #  ┌───────────── minute (0 - 59)
  #  │ ┌───────────── hour (0 - 23)
  #  │ │ ┌───────────── day of the month (1 - 31)
  #  │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #  │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #  │ │ │ │ │
  #  │ │ │ │ │
  #  │ │ │ │ │
  #  * * * * *
  #--分时日月周 
  #自动清理：每周1,3,5早上2点30分(UTC 18:30) --分 时 日 月 周
  #- cron: 30 18 * * 1,3,5
  schedule:
    - cron: 30 18 * * 3
  #手动清理
  workflow_dispatch:
    inputs:
      NUMBER:
        default: '4'
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: ${{inputs.NUMBER || '4'}}
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
